# Generated by Django 4.0.3 on 2022-04-07 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Note',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField()),
                ('note', models.TextField()),
                ('username', models.CharField(max_length=200)),
                ('isPinned', models.BooleanField()),
            ],
        ),
    ]
